import sys

import lsst_sphinx_bootstrap_theme


# Work around Sphinx bug related to large and highly-nested source files
sys.setrecursionlimit(2000)

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "documenteer.sphinxext",
    "sphinx-prompt",
]
# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "Vera C. Rubin Observatory Operations Documentation"
copyright = "2020 Association of Universities for Research in Astronomy (AURA), Inc."
author = "Rubin Observatory"

version = "Current"
release = version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = [
    "_build",
    "README.rst",
    ".venv",
    "venv",
    "project/Templates/Template-Folder",
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# The reST default role cross-links Python (used for this markup: `text`)
default_role = "py:obj"

# Intersphinx
intersphinx_mapping = {
    'obs-controls': ('https://obs-controls.lsst.io', None)
    # 'python': ('https://docs.python.org/3/', None),
}

# Add substitions or link targets that you want on every page.
rst_epilog = """

"""

# -- Options for linkcheck builder ----------------------------------------

linkcheck_retries = 2
linkcheck_timeout = 5  # seconds
linkcheck_ignore = [
    r"^http://localhost",
    r"http://amor01.cp.lsst.org/login",
]

# -- Options for HTML output ----------------------------------------------

templates_path = ["_templates", lsst_sphinx_bootstrap_theme.get_html_templates_path()]

html_theme = "lsst_sphinx_bootstrap_theme"
html_theme_path = [lsst_sphinx_bootstrap_theme.get_html_theme_path()]


html_context = {
    # Enable "Edit in GitHub" link
    "display_github": True,
    # https://{{ github_host|default("github.com") }}/{{ github_user }}/
    #     {{ github_repo }}/blob/
    #     {{ github_version }}{{ conf_py_path }}{{ pagename }}{{ suffix }}
    "github_user": "lsst-ts",
    "github_repo": "observatory-ops-docs",
    "conf_py_path": "",
    # TRAVIS_BRANCH is available in CI, but master is a safe default
    "github_version": "master" + "/",
}

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {"logotext": project}

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
html_title = project

# A shorter title for the navigation bar.  Default is the same as html_title.
html_short_title = project

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = []

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = False

linkcheck_ignore = [
    r"http://amor01.cp.lsst.org/*",
    r"http://localhost:\d+/*",
    r"https://base-lsp.lsst.codes/*",
    r"https://chronograf-base-efd.lsst.codes/",
    r"https://chronograf-summit-efd.lsst.codes/",
    r"https://chronograf-tucson-teststand-efd.lsst.codes/",
    r"https://jira.lsstcorp.org/*",
    r"https://lsst-argocd-nts-efd.ncsa.illinois.edu/",
    r"https://lsst-chronograf-nts-efd.ncsa.illinois.edu/",
    r"https://lsst-nts-k8s.ncsa.illinois.edu/",
    r"https://summit-lsp.lsst.codes/*",
    r"https://tucson-teststand.lsst.codes/*",
    r"https://www.jenkins.io/doc/book/glossary/#controller",
    r"https://www.jenkins.io/doc/book/glossary/#agent",
    r"https://www.jenkins.io/doc/book/glossary/#pipeline",
    r"https://www.jenkins.io/doc/book/glossary/#project",
    r"https://anaconda.org",
    r"https://lsst-argocd-nts-efd.ncsa.illinois.edu/argo-cd",
    r"https://base-lsp.lsst.codes/argo-cd",
    r"https://tucson-teststand.lsst.codes/argo-cd",
    r"https://summit-lsp.lsst.codes/argo-cd",
    r"https://rancher.cp.lsst.org/login",
    r"https://www.adlinktech.com/en/vortex-opensplice-data-distribution-service",
    r"https://developers.google.com/style",
]
