name: Deployment

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install graphviz
        run: sudo apt-get install -y graphviz

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check links
        run: make linkcheck

      - name: Build site
        run: make html

      - name: Upload documentation
        uses: lsst-sqre/ltd-upload@v1
        with:
          project: "obs-ops"
          dir: "_build/html"
          username: ts-ci
          password: ${{ secrets.LTD_PASSWORD }}